// @ts-check
'use strict';

const { deepMergeConfig } = require('@-xun/symbiote/assets');

const {
  assertEnvironment,
  moduleExport
} = require('@-xun/symbiote/assets/babel.config.cjs');

const { createDebugLogger } = require('rejoinder');

const debug = createDebugLogger({ namespace: 'symbiote:config:babel' });

const config = deepMergeConfig(
  moduleExport({
    derivedAliases: getBabelAliases(),
    ...assertEnvironment({ projectRoot: __dirname })
  }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
    //
    // You may wish to enable explicit exports references for improved testing
    // DX, but be aware that it is currently a wee buggy as of 5/2025 (fix it!)
    //
    // env: {
    //   test: {
    //     plugins: ['babel-plugin-explicit-exports-references']
    //   }
    // }
  }
);

module.exports = config;
debug('exported config: %O', module.exports);

function getBabelAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+mdast\\x2dutil\\x2dhidden:(.+)$':
      './packages/mdast-util-hidden/src/$1',
    '^multiverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      './packages/mdast-util-tight-comments/src/$1',
    '^multiverse\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      './packages/remark-capitalize-headings/src/$1',
    '^multiverse\\+remark\\x2dignore:(.+)$': './packages/remark-ignore/src/$1',
    '^multiverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      './packages/remark-lint-fenced-code-flag-case/src/$1',
    '^multiverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      './packages/remark-lint-heading-word-length/src/$1',
    '^multiverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      './packages/remark-lint-list-item-style/src/$1',
    '^multiverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      './packages/remark-remove-unused-definitions/src/$1',
    '^multiverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      './packages/remark-remove-url-trailing-slash/src/$1',
    '^multiverse\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      './packages/remark-renumber-references/src/$1',
    '^multiverse\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      './packages/remark-sort-definitions/src/$1',
    '^multiverse\\+remark\\x2dtight\\x2dcomments:(.+)$':
      './packages/remark-tight-comments/src/$1',
    '^multiverse\\+mdast\\x2dutil\\x2dhidden$':
      './packages/mdast-util-hidden/src/index.js',
    '^multiverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments$':
      './packages/mdast-util-tight-comments/src/index.js',
    '^multiverse\\+remark\\x2dcapitalize\\x2dheadings$':
      './packages/remark-capitalize-headings/src/index.js',
    '^multiverse\\+remark\\x2dignore$': './packages/remark-ignore/src/index.js',
    '^multiverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase$':
      './packages/remark-lint-fenced-code-flag-case/src/index.js',
    '^multiverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength$':
      './packages/remark-lint-heading-word-length/src/index.js',
    '^multiverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle$':
      './packages/remark-lint-list-item-style/src/index.js',
    '^multiverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions$':
      './packages/remark-remove-unused-definitions/src/index.js',
    '^multiverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash$':
      './packages/remark-remove-url-trailing-slash/src/index.js',
    '^multiverse\\+remark\\x2drenumber\\x2dreferences$':
      './packages/remark-renumber-references/src/index.js',
    '^multiverse\\+remark\\x2dsort\\x2ddefinitions$':
      './packages/remark-sort-definitions/src/index.js',
    '^multiverse\\+remark\\x2dtight\\x2dcomments$':
      './packages/remark-tight-comments/src/index.js',
    '^universe\\+mdast\\x2dutil\\x2dhidden:(.+)$': './packages/mdast-util-hidden/src/$1',
    '^universe\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      './packages/mdast-util-tight-comments/src/$1',
    '^universe\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      './packages/remark-capitalize-headings/src/$1',
    '^universe\\+remark\\x2dignore:(.+)$': './packages/remark-ignore/src/$1',
    '^universe\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      './packages/remark-lint-fenced-code-flag-case/src/$1',
    '^universe\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      './packages/remark-lint-heading-word-length/src/$1',
    '^universe\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      './packages/remark-lint-list-item-style/src/$1',
    '^universe\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      './packages/remark-remove-unused-definitions/src/$1',
    '^universe\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      './packages/remark-remove-url-trailing-slash/src/$1',
    '^universe\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      './packages/remark-renumber-references/src/$1',
    '^universe\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      './packages/remark-sort-definitions/src/$1',
    '^universe\\+remark\\x2dtight\\x2dcomments:(.+)$':
      './packages/remark-tight-comments/src/$1',
    '^universe\\+mdast\\x2dutil\\x2dhidden$':
      './packages/mdast-util-hidden/src/index.js',
    '^universe\\+mdast\\x2dutil\\x2dtight\\x2dcomments$':
      './packages/mdast-util-tight-comments/src/index.js',
    '^universe\\+remark\\x2dcapitalize\\x2dheadings$':
      './packages/remark-capitalize-headings/src/index.js',
    '^universe\\+remark\\x2dignore$': './packages/remark-ignore/src/index.js',
    '^universe\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase$':
      './packages/remark-lint-fenced-code-flag-case/src/index.js',
    '^universe\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength$':
      './packages/remark-lint-heading-word-length/src/index.js',
    '^universe\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle$':
      './packages/remark-lint-list-item-style/src/index.js',
    '^universe\\+remark\\x2dremove\\x2dunused\\x2ddefinitions$':
      './packages/remark-remove-unused-definitions/src/index.js',
    '^universe\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash$':
      './packages/remark-remove-url-trailing-slash/src/index.js',
    '^universe\\+remark\\x2drenumber\\x2dreferences$':
      './packages/remark-renumber-references/src/index.js',
    '^universe\\+remark\\x2dsort\\x2ddefinitions$':
      './packages/remark-sort-definitions/src/index.js',
    '^universe\\+remark\\x2dtight\\x2dcomments$':
      './packages/remark-tight-comments/src/index.js',
    '^universe:(.+)$': './src/$1',
    '^universe$': './src/index.js',
    '^testverse\\+mdast\\x2dutil\\x2dhidden:(.+)$':
      './packages/mdast-util-hidden/test/$1',
    '^testverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      './packages/mdast-util-tight-comments/test/$1',
    '^testverse\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      './packages/remark-capitalize-headings/test/$1',
    '^testverse\\+remark\\x2dignore:(.+)$': './packages/remark-ignore/test/$1',
    '^testverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      './packages/remark-lint-fenced-code-flag-case/test/$1',
    '^testverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      './packages/remark-lint-heading-word-length/test/$1',
    '^testverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      './packages/remark-lint-list-item-style/test/$1',
    '^testverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      './packages/remark-remove-unused-definitions/test/$1',
    '^testverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      './packages/remark-remove-url-trailing-slash/test/$1',
    '^testverse\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      './packages/remark-renumber-references/test/$1',
    '^testverse\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      './packages/remark-sort-definitions/test/$1',
    '^testverse\\+remark\\x2dtight\\x2dcomments:(.+)$':
      './packages/remark-tight-comments/test/$1',
    '^testverse:(.+)$': './test/$1',
    '^typeverse:(.+)$': './types/$1',
    '^rootverse\\+mdast\\x2dutil\\x2dhidden:(.+)$': './packages/mdast-util-hidden/$1',
    '^rootverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      './packages/mdast-util-tight-comments/$1',
    '^rootverse\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      './packages/remark-capitalize-headings/$1',
    '^rootverse\\+remark\\x2dignore:(.+)$': './packages/remark-ignore/$1',
    '^rootverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      './packages/remark-lint-fenced-code-flag-case/$1',
    '^rootverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      './packages/remark-lint-heading-word-length/$1',
    '^rootverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      './packages/remark-lint-list-item-style/$1',
    '^rootverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      './packages/remark-remove-unused-definitions/$1',
    '^rootverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      './packages/remark-remove-url-trailing-slash/$1',
    '^rootverse\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      './packages/remark-renumber-references/$1',
    '^rootverse\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      './packages/remark-sort-definitions/$1',
    '^rootverse\\+remark\\x2dtight\\x2dcomments:(.+)$':
      './packages/remark-tight-comments/$1',
    '^rootverse:(.+)$': './$1'
  };
}
