// @ts-check

import {
  assertEnvironment,
  moduleExport
} from '@-xun/symbiote/assets/eslint.config.mjs';

import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:eslint' });

const config = await moduleExport({
  derivedAliases: getEslintAliases(),
  ...(await assertEnvironment())
});

/* Add custom config objects here, such as those disabling certain rules */
config
  .push
  // ? Paths listed here are ignored by Eslint and related tooling.
  // { ignores: [] },
  // * Configs applying to both JavaScript & TypeScript files (all extensions)
  // ? Keep in mind that JS files can use @ts-check and "become" TS files,
  // ? hence the existence of this block. Logically, most rules should be
  // ? loaded here.
  // ...[
  //   { ...eslintPluginReactConfigs.flat.recommended, name: 'react:recommended' },
  //   // ? For react@>=17
  //   { ...eslintPluginReactConfigs.flat['jsx-runtime'], name: 'react:jsx-runtime' },
  //   {
  //     ...eslintPluginReactHooksConfigs['recommended-latest'],
  //     name: 'react-hooks:recommended-latest'
  //   },
  //   { ...eslintPluginJsxA11yFlatConfigs.recommended, name: 'jsx-a11y:recommended' }
  // ].flatMap((configs) =>
  //   overwriteProperty(configs, 'files', [
  //     `**/*.{ts,cts,mts,tsx}`
  //   ])
  // ),
  // {
  //   rules: {
  //     'unicorn/no-keyword-prefix': 'off',
  //     'no-restricted-syntax': 'off'
  //   }
  // }
  ();

export default config;

debug('exported config: %O', config);

function getEslintAliases() {
  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return [
    ['multiverse+mdast-util-hidden:*', './packages/mdast-util-hidden/src/*'],
    [
      'multiverse+mdast-util-tight-comments:*',
      './packages/mdast-util-tight-comments/src/*'
    ],
    [
      'multiverse+remark-capitalize-headings:*',
      './packages/remark-capitalize-headings/src/*'
    ],
    ['multiverse+remark-ignore:*', './packages/remark-ignore/src/*'],
    [
      'multiverse+remark-lint-fenced-code-flag-case:*',
      './packages/remark-lint-fenced-code-flag-case/src/*'
    ],
    [
      'multiverse+remark-lint-heading-word-length:*',
      './packages/remark-lint-heading-word-length/src/*'
    ],
    [
      'multiverse+remark-lint-list-item-style:*',
      './packages/remark-lint-list-item-style/src/*'
    ],
    [
      'multiverse+remark-remove-unused-definitions:*',
      './packages/remark-remove-unused-definitions/src/*'
    ],
    [
      'multiverse+remark-remove-url-trailing-slash:*',
      './packages/remark-remove-url-trailing-slash/src/*'
    ],
    [
      'multiverse+remark-renumber-references:*',
      './packages/remark-renumber-references/src/*'
    ],
    ['multiverse+remark-sort-definitions:*', './packages/remark-sort-definitions/src/*'],
    ['multiverse+remark-tight-comments:*', './packages/remark-tight-comments/src/*'],
    ['multiverse+mdast-util-hidden', './packages/mdast-util-hidden/src/index.ts'],
    [
      'multiverse+mdast-util-tight-comments',
      './packages/mdast-util-tight-comments/src/index.ts'
    ],
    [
      'multiverse+remark-capitalize-headings',
      './packages/remark-capitalize-headings/src/index.ts'
    ],
    ['multiverse+remark-ignore', './packages/remark-ignore/src/index.ts'],
    [
      'multiverse+remark-lint-fenced-code-flag-case',
      './packages/remark-lint-fenced-code-flag-case/src/index.ts'
    ],
    [
      'multiverse+remark-lint-heading-word-length',
      './packages/remark-lint-heading-word-length/src/index.ts'
    ],
    [
      'multiverse+remark-lint-list-item-style',
      './packages/remark-lint-list-item-style/src/index.ts'
    ],
    [
      'multiverse+remark-remove-unused-definitions',
      './packages/remark-remove-unused-definitions/src/index.ts'
    ],
    [
      'multiverse+remark-remove-url-trailing-slash',
      './packages/remark-remove-url-trailing-slash/src/index.ts'
    ],
    [
      'multiverse+remark-renumber-references',
      './packages/remark-renumber-references/src/index.ts'
    ],
    [
      'multiverse+remark-sort-definitions',
      './packages/remark-sort-definitions/src/index.ts'
    ],
    [
      'multiverse+remark-tight-comments',
      './packages/remark-tight-comments/src/index.ts'
    ],
    ['rootverse+mdast-util-hidden:*', './packages/mdast-util-hidden/*'],
    ['rootverse+mdast-util-tight-comments:*', './packages/mdast-util-tight-comments/*'],
    [
      'rootverse+remark-capitalize-headings:*',
      './packages/remark-capitalize-headings/*'
    ],
    ['rootverse+remark-ignore:*', './packages/remark-ignore/*'],
    [
      'rootverse+remark-lint-fenced-code-flag-case:*',
      './packages/remark-lint-fenced-code-flag-case/*'
    ],
    [
      'rootverse+remark-lint-heading-word-length:*',
      './packages/remark-lint-heading-word-length/*'
    ],
    [
      'rootverse+remark-lint-list-item-style:*',
      './packages/remark-lint-list-item-style/*'
    ],
    [
      'rootverse+remark-remove-unused-definitions:*',
      './packages/remark-remove-unused-definitions/*'
    ],
    [
      'rootverse+remark-remove-url-trailing-slash:*',
      './packages/remark-remove-url-trailing-slash/*'
    ],
    [
      'rootverse+remark-renumber-references:*',
      './packages/remark-renumber-references/*'
    ],
    ['rootverse+remark-sort-definitions:*', './packages/remark-sort-definitions/*'],
    ['rootverse+remark-tight-comments:*', './packages/remark-tight-comments/*'],
    ['rootverse:*', './*'],
    ['universe+mdast-util-hidden:*', './packages/mdast-util-hidden/src/*'],
    [
      'universe+mdast-util-tight-comments:*',
      './packages/mdast-util-tight-comments/src/*'
    ],
    [
      'universe+remark-capitalize-headings:*',
      './packages/remark-capitalize-headings/src/*'
    ],
    ['universe+remark-ignore:*', './packages/remark-ignore/src/*'],
    [
      'universe+remark-lint-fenced-code-flag-case:*',
      './packages/remark-lint-fenced-code-flag-case/src/*'
    ],
    [
      'universe+remark-lint-heading-word-length:*',
      './packages/remark-lint-heading-word-length/src/*'
    ],
    [
      'universe+remark-lint-list-item-style:*',
      './packages/remark-lint-list-item-style/src/*'
    ],
    [
      'universe+remark-remove-unused-definitions:*',
      './packages/remark-remove-unused-definitions/src/*'
    ],
    [
      'universe+remark-remove-url-trailing-slash:*',
      './packages/remark-remove-url-trailing-slash/src/*'
    ],
    [
      'universe+remark-renumber-references:*',
      './packages/remark-renumber-references/src/*'
    ],
    ['universe+remark-sort-definitions:*', './packages/remark-sort-definitions/src/*'],
    ['universe+remark-tight-comments:*', './packages/remark-tight-comments/src/*'],
    ['universe+mdast-util-hidden', './packages/mdast-util-hidden/src/index.ts'],
    [
      'universe+mdast-util-tight-comments',
      './packages/mdast-util-tight-comments/src/index.ts'
    ],
    [
      'universe+remark-capitalize-headings',
      './packages/remark-capitalize-headings/src/index.ts'
    ],
    ['universe+remark-ignore', './packages/remark-ignore/src/index.ts'],
    [
      'universe+remark-lint-fenced-code-flag-case',
      './packages/remark-lint-fenced-code-flag-case/src/index.ts'
    ],
    [
      'universe+remark-lint-heading-word-length',
      './packages/remark-lint-heading-word-length/src/index.ts'
    ],
    [
      'universe+remark-lint-list-item-style',
      './packages/remark-lint-list-item-style/src/index.ts'
    ],
    [
      'universe+remark-remove-unused-definitions',
      './packages/remark-remove-unused-definitions/src/index.ts'
    ],
    [
      'universe+remark-remove-url-trailing-slash',
      './packages/remark-remove-url-trailing-slash/src/index.ts'
    ],
    [
      'universe+remark-renumber-references',
      './packages/remark-renumber-references/src/index.ts'
    ],
    [
      'universe+remark-sort-definitions',
      './packages/remark-sort-definitions/src/index.ts'
    ],
    ['universe+remark-tight-comments', './packages/remark-tight-comments/src/index.ts'],
    ['universe:*', './src/*'],
    ['universe', './src/index.ts'],
    ['testverse+mdast-util-hidden:*', './packages/mdast-util-hidden/test/*'],
    [
      'testverse+mdast-util-tight-comments:*',
      './packages/mdast-util-tight-comments/test/*'
    ],
    [
      'testverse+remark-capitalize-headings:*',
      './packages/remark-capitalize-headings/test/*'
    ],
    ['testverse+remark-ignore:*', './packages/remark-ignore/test/*'],
    [
      'testverse+remark-lint-fenced-code-flag-case:*',
      './packages/remark-lint-fenced-code-flag-case/test/*'
    ],
    [
      'testverse+remark-lint-heading-word-length:*',
      './packages/remark-lint-heading-word-length/test/*'
    ],
    [
      'testverse+remark-lint-list-item-style:*',
      './packages/remark-lint-list-item-style/test/*'
    ],
    [
      'testverse+remark-remove-unused-definitions:*',
      './packages/remark-remove-unused-definitions/test/*'
    ],
    [
      'testverse+remark-remove-url-trailing-slash:*',
      './packages/remark-remove-url-trailing-slash/test/*'
    ],
    [
      'testverse+remark-renumber-references:*',
      './packages/remark-renumber-references/test/*'
    ],
    ['testverse+remark-sort-definitions:*', './packages/remark-sort-definitions/test/*'],
    ['testverse+remark-tight-comments:*', './packages/remark-tight-comments/test/*'],
    ['testverse:*', './test/*'],
    ['typeverse:*', './types/*']
  ];
}
