// @ts-check
'use strict';

import { deepMergeConfig } from '@-xun/symbiote/assets';
import { assertEnvironment, moduleExport } from '@-xun/symbiote/assets/jest.config.mjs';
import { createDebugLogger } from 'rejoinder';

const debug = createDebugLogger({ namespace: 'symbiote:config:jest' });

const config = deepMergeConfig(
  moduleExport({ derivedAliases: getJestAliases(), ...assertEnvironment() }),
  {
    // Any custom configs here will be deep merged with moduleExport's result
  }
);

export default config;

debug('exported config: %O', config);

function getJestAliases() {
  const extension = process.env.SYMBIOTE_TEST_JEST_TRANSPILED ? 'js' : 'ts';

  // ! These aliases are auto-generated by symbiote. Instead of modifying them
  // ! directly, consider regenerating aliases across the entire project with:
  // ! `npx symbiote project renovate --regenerate-assets --assets-preset ...`
  return {
    '^multiverse\\+mdast\\x2dutil\\x2dhidden:(.+)$':
      '<rootDir>/packages/mdast-util-hidden/src/$1',
    '^multiverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/mdast-util-tight-comments/src/$1',
    '^multiverse\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      '<rootDir>/packages/remark-capitalize-headings/src/$1',
    '^multiverse\\+remark\\x2dignore:(.+)$': '<rootDir>/packages/remark-ignore/src/$1',
    '^multiverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      '<rootDir>/packages/remark-lint-fenced-code-flag-case/src/$1',
    '^multiverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      '<rootDir>/packages/remark-lint-heading-word-length/src/$1',
    '^multiverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      '<rootDir>/packages/remark-lint-list-item-style/src/$1',
    '^multiverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-remove-unused-definitions/src/$1',
    '^multiverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      '<rootDir>/packages/remark-remove-url-trailing-slash/src/$1',
    '^multiverse\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      '<rootDir>/packages/remark-renumber-references/src/$1',
    '^multiverse\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-sort-definitions/src/$1',
    '^multiverse\\+remark\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/remark-tight-comments/src/$1',
    '^multiverse\\+mdast\\x2dutil\\x2dhidden$': `<rootDir>/packages/mdast-util-hidden/src/index.${extension}`,
    '^multiverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments$': `<rootDir>/packages/mdast-util-tight-comments/src/index.${extension}`,
    '^multiverse\\+remark\\x2dcapitalize\\x2dheadings$': `<rootDir>/packages/remark-capitalize-headings/src/index.${extension}`,
    '^multiverse\\+remark\\x2dignore$': `<rootDir>/packages/remark-ignore/src/index.${extension}`,
    '^multiverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase$': `<rootDir>/packages/remark-lint-fenced-code-flag-case/src/index.${extension}`,
    '^multiverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength$': `<rootDir>/packages/remark-lint-heading-word-length/src/index.${extension}`,
    '^multiverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle$': `<rootDir>/packages/remark-lint-list-item-style/src/index.${extension}`,
    '^multiverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions$': `<rootDir>/packages/remark-remove-unused-definitions/src/index.${extension}`,
    '^multiverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash$': `<rootDir>/packages/remark-remove-url-trailing-slash/src/index.${extension}`,
    '^multiverse\\+remark\\x2drenumber\\x2dreferences$': `<rootDir>/packages/remark-renumber-references/src/index.${extension}`,
    '^multiverse\\+remark\\x2dsort\\x2ddefinitions$': `<rootDir>/packages/remark-sort-definitions/src/index.${extension}`,
    '^multiverse\\+remark\\x2dtight\\x2dcomments$': `<rootDir>/packages/remark-tight-comments/src/index.${extension}`,
    '^universe\\+mdast\\x2dutil\\x2dhidden:(.+)$':
      '<rootDir>/packages/mdast-util-hidden/src/$1',
    '^universe\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/mdast-util-tight-comments/src/$1',
    '^universe\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      '<rootDir>/packages/remark-capitalize-headings/src/$1',
    '^universe\\+remark\\x2dignore:(.+)$': '<rootDir>/packages/remark-ignore/src/$1',
    '^universe\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      '<rootDir>/packages/remark-lint-fenced-code-flag-case/src/$1',
    '^universe\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      '<rootDir>/packages/remark-lint-heading-word-length/src/$1',
    '^universe\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      '<rootDir>/packages/remark-lint-list-item-style/src/$1',
    '^universe\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-remove-unused-definitions/src/$1',
    '^universe\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      '<rootDir>/packages/remark-remove-url-trailing-slash/src/$1',
    '^universe\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      '<rootDir>/packages/remark-renumber-references/src/$1',
    '^universe\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-sort-definitions/src/$1',
    '^universe\\+remark\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/remark-tight-comments/src/$1',
    '^universe\\+mdast\\x2dutil\\x2dhidden$': `<rootDir>/packages/mdast-util-hidden/src/index.${extension}`,
    '^universe\\+mdast\\x2dutil\\x2dtight\\x2dcomments$': `<rootDir>/packages/mdast-util-tight-comments/src/index.${extension}`,
    '^universe\\+remark\\x2dcapitalize\\x2dheadings$': `<rootDir>/packages/remark-capitalize-headings/src/index.${extension}`,
    '^universe\\+remark\\x2dignore$': `<rootDir>/packages/remark-ignore/src/index.${extension}`,
    '^universe\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase$': `<rootDir>/packages/remark-lint-fenced-code-flag-case/src/index.${extension}`,
    '^universe\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength$': `<rootDir>/packages/remark-lint-heading-word-length/src/index.${extension}`,
    '^universe\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle$': `<rootDir>/packages/remark-lint-list-item-style/src/index.${extension}`,
    '^universe\\+remark\\x2dremove\\x2dunused\\x2ddefinitions$': `<rootDir>/packages/remark-remove-unused-definitions/src/index.${extension}`,
    '^universe\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash$': `<rootDir>/packages/remark-remove-url-trailing-slash/src/index.${extension}`,
    '^universe\\+remark\\x2drenumber\\x2dreferences$': `<rootDir>/packages/remark-renumber-references/src/index.${extension}`,
    '^universe\\+remark\\x2dsort\\x2ddefinitions$': `<rootDir>/packages/remark-sort-definitions/src/index.${extension}`,
    '^universe\\+remark\\x2dtight\\x2dcomments$': `<rootDir>/packages/remark-tight-comments/src/index.${extension}`,
    '^universe:(.+)$': '<rootDir>/src/$1',
    '^universe$': `<rootDir>/src/index.${extension}`,
    '^testverse\\+mdast\\x2dutil\\x2dhidden:(.+)$':
      '<rootDir>/packages/mdast-util-hidden/test/$1',
    '^testverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/mdast-util-tight-comments/test/$1',
    '^testverse\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      '<rootDir>/packages/remark-capitalize-headings/test/$1',
    '^testverse\\+remark\\x2dignore:(.+)$': '<rootDir>/packages/remark-ignore/test/$1',
    '^testverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      '<rootDir>/packages/remark-lint-fenced-code-flag-case/test/$1',
    '^testverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      '<rootDir>/packages/remark-lint-heading-word-length/test/$1',
    '^testverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      '<rootDir>/packages/remark-lint-list-item-style/test/$1',
    '^testverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-remove-unused-definitions/test/$1',
    '^testverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      '<rootDir>/packages/remark-remove-url-trailing-slash/test/$1',
    '^testverse\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      '<rootDir>/packages/remark-renumber-references/test/$1',
    '^testverse\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-sort-definitions/test/$1',
    '^testverse\\+remark\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/remark-tight-comments/test/$1',
    '^testverse:(.+)$': '<rootDir>/test/$1',
    '^typeverse:(.+)$': '<rootDir>/types/$1',
    '^rootverse\\+mdast\\x2dutil\\x2dhidden:(.+)$':
      '<rootDir>/packages/mdast-util-hidden/$1',
    '^rootverse\\+mdast\\x2dutil\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/mdast-util-tight-comments/$1',
    '^rootverse\\+remark\\x2dcapitalize\\x2dheadings:(.+)$':
      '<rootDir>/packages/remark-capitalize-headings/$1',
    '^rootverse\\+remark\\x2dignore:(.+)$': '<rootDir>/packages/remark-ignore/$1',
    '^rootverse\\+remark\\x2dlint\\x2dfenced\\x2dcode\\x2dflag\\x2dcase:(.+)$':
      '<rootDir>/packages/remark-lint-fenced-code-flag-case/$1',
    '^rootverse\\+remark\\x2dlint\\x2dheading\\x2dword\\x2dlength:(.+)$':
      '<rootDir>/packages/remark-lint-heading-word-length/$1',
    '^rootverse\\+remark\\x2dlint\\x2dlist\\x2ditem\\x2dstyle:(.+)$':
      '<rootDir>/packages/remark-lint-list-item-style/$1',
    '^rootverse\\+remark\\x2dremove\\x2dunused\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-remove-unused-definitions/$1',
    '^rootverse\\+remark\\x2dremove\\x2durl\\x2dtrailing\\x2dslash:(.+)$':
      '<rootDir>/packages/remark-remove-url-trailing-slash/$1',
    '^rootverse\\+remark\\x2drenumber\\x2dreferences:(.+)$':
      '<rootDir>/packages/remark-renumber-references/$1',
    '^rootverse\\+remark\\x2dsort\\x2ddefinitions:(.+)$':
      '<rootDir>/packages/remark-sort-definitions/$1',
    '^rootverse\\+remark\\x2dtight\\x2dcomments:(.+)$':
      '<rootDir>/packages/remark-tight-comments/$1',
    '^rootverse:(.+)$': '<rootDir>/$1'
  };
}
